<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0-rc.2.25502.107" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0-rc.2.25502.107" />
      <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.0-rc.2.25502.107" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.0-rc.2.25502.107" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CoinbaseFetcher.Domain\CoinbaseFetcher.Domain.csproj" />
    </ItemGroup>

</Project>
